/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emedi;

/**
 *
 * @author sria
 */
public class About_Astro_03 extends javax.swing.JFrame {

    /**
     * Creates new form About_Astro_03
     */
    public About_Astro_03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        about_astro_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        about_banner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About Astro 0.3");
        setMaximumSize(new java.awt.Dimension(1026, 583));
        setMinimumSize(new java.awt.Dimension(1026, 583));
        setPreferredSize(new java.awt.Dimension(1026, 583));
        getContentPane().setLayout(null);

        about_astro_label.setFont(new java.awt.Font("Purisa", 3, 36)); // NOI18N
        about_astro_label.setForeground(new java.awt.Color(254, 254, 254));
        about_astro_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about_astro.jpg"))); // NOI18N
        about_astro_label.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(about_astro_label);
        about_astro_label.setBounds(10, 10, 260, 50);

        jLabel1.setBackground(new java.awt.Color(176, 157, 157));
        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 250, 250));
        jLabel1.setText("3 Members");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 60, 240, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Oasik.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 180, 290, 230);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jakaria.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 180, 320, 220);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jannat.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 400, 300, 190);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Using.jpg"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 3, true));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(720, 400, 282, 160);

        about_banner.setForeground(new java.awt.Color(1, 1, 1));
        about_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banner_about.jpg"))); // NOI18N
        about_banner.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(206, 196, 196), new java.awt.Color(36, 19, 19), null, null));
        about_banner.setMaximumSize(new java.awt.Dimension(1026, 583));
        about_banner.setMinimumSize(new java.awt.Dimension(1026, 583));
        about_banner.setPreferredSize(new java.awt.Dimension(1026, 583));
        getContentPane().add(about_banner);
        about_banner.setBounds(0, 0, 1030, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About_Astro_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About_Astro_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About_Astro_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About_Astro_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new About_Astro_03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about_astro_label;
    private javax.swing.JLabel about_banner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
