/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emedi;

/**
 *
 * @author sria
 */
public class consult extends javax.swing.JFrame {

    /**
     * Creates new form consult
     */
    public consult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consult_label = new javax.swing.JLabel();
        specialist_label = new javax.swing.JLabel();
        specialist = new javax.swing.JComboBox<>();
        doctor_name = new javax.swing.JTextField();
        Doctor_name_label = new javax.swing.JLabel();
        degree = new javax.swing.JTextField();
        work_place = new javax.swing.JTextField();
        cell_no = new javax.swing.JTextField();
        work_place_label = new javax.swing.JLabel();
        degree_label = new javax.swing.JLabel();
        cell_no_label = new javax.swing.JLabel();
        e_mail_label = new javax.swing.JLabel();
        e_mail = new javax.swing.JTextField();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consult With A Doctor");
        setMaximumSize(new java.awt.Dimension(1026, 583));
        setMinimumSize(new java.awt.Dimension(1026, 583));
        setPreferredSize(new java.awt.Dimension(1026, 583));
        getContentPane().setLayout(null);

        consult_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c_with_doc.jpg"))); // NOI18N
        getContentPane().add(consult_label);
        consult_label.setBounds(250, 10, 320, 40);

        specialist_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/specialist.png"))); // NOI18N
        getContentPane().add(specialist_label);
        specialist_label.setBounds(220, 120, 100, 40);

        specialist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select_Specialist", "Psychiatrist", "Pediatrician", "Orthopedist", "Allergist" }));
        specialist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialistActionPerformed(evt);
            }
        });
        getContentPane().add(specialist);
        specialist.setBounds(340, 130, 190, 27);

        doctor_name.setBackground(new java.awt.Color(254, 254, 254));
        getContentPane().add(doctor_name);
        doctor_name.setBounds(10, 330, 250, 40);

        Doctor_name_label.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Doctor_name_label.setForeground(new java.awt.Color(1, 1, 1));
        Doctor_name_label.setText("Doctor's Name :");
        getContentPane().add(Doctor_name_label);
        Doctor_name_label.setBounds(10, 300, 150, 30);
        getContentPane().add(degree);
        degree.setBounds(320, 340, 170, 30);

        work_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                work_placeActionPerformed(evt);
            }
        });
        getContentPane().add(work_place);
        work_place.setBounds(10, 410, 240, 30);
        getContentPane().add(cell_no);
        cell_no.setBounds(10, 470, 240, 30);

        work_place_label.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        work_place_label.setForeground(new java.awt.Color(1, 1, 1));
        work_place_label.setText("Work Place : ");
        getContentPane().add(work_place_label);
        work_place_label.setBounds(10, 380, 150, 20);

        degree_label.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        degree_label.setForeground(new java.awt.Color(1, 1, 1));
        degree_label.setText("Degree :");
        getContentPane().add(degree_label);
        degree_label.setBounds(360, 310, 80, 20);

        cell_no_label.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cell_no_label.setForeground(new java.awt.Color(1, 1, 1));
        cell_no_label.setText("Cell No :");
        getContentPane().add(cell_no_label);
        cell_no_label.setBounds(10, 441, 100, 20);

        e_mail_label.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        e_mail_label.setForeground(new java.awt.Color(1, 1, 1));
        e_mail_label.setText("E-Mail :");
        getContentPane().add(e_mail_label);
        e_mail_label.setBounds(10, 510, 70, 21);
        getContentPane().add(e_mail);
        e_mail.setBounds(10, 530, 240, 30);

        background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banner_treatment.jpg"))); // NOI18N
        background_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background_label.setMaximumSize(new java.awt.Dimension(1026, 583));
        background_label.setMinimumSize(new java.awt.Dimension(1026, 583));
        background_label.setPreferredSize(new java.awt.Dimension(1026, 583));
        getContentPane().add(background_label);
        background_label.setBounds(0, 0, 1026, 583);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void work_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_work_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_work_placeActionPerformed

    private void specialistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialistActionPerformed
        // TODO add your handling code here:
        
        if (specialist.getSelectedItem().equals("Psychiatrist"))
        {
            Object[] sychia = null;
            String npsy=String.format(" Dr. Abul Kalam Azad", sychia);
            doctor_name.setText(npsy);
            
            String dpsy=String.format("MBBS, FRCS P-1", sychia);
            degree. setText(dpsy);
            
            String wpsy=String.format("Dhaka Medicle College and Hospital", sychia);
            work_place.setText(wpsy);
            
            String cpsy=String.format("017*******", sychia);
            cell_no.setText(cpsy);
            
            String epsy=String.format("akazad1989@gmail.com", sychia);
            e_mail.setText(epsy);
            
        }
        
        if (specialist.getSelectedItem().equals("Pediatrician"))
        {
            Object[] Pedi = null;
            String nPedi=String.format(" Dr. Kashru Ahmed", Pedi);
            doctor_name.setText(nPedi);
            
            String dPedi=String.format("MBBS", Pedi);
            degree. setText(dPedi);
            
            String wPedi=String.format("Habiganj sadar hospital", Pedi);
            work_place.setText(wPedi);
            
            String cPedi=String.format("017*******", Pedi);
            cell_no.setText(cPedi);
            
            String ePedi=String.format("kahmed1122@gmail.com", Pedi);
            e_mail.setText(ePedi);
            
        }
    }//GEN-LAST:event_specialistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new consult().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Doctor_name_label;
    private javax.swing.JLabel background_label;
    private javax.swing.JTextField cell_no;
    private javax.swing.JLabel cell_no_label;
    private javax.swing.JLabel consult_label;
    private javax.swing.JTextField degree;
    private javax.swing.JLabel degree_label;
    private javax.swing.JTextField doctor_name;
    private javax.swing.JTextField e_mail;
    private javax.swing.JLabel e_mail_label;
    private javax.swing.JComboBox<String> specialist;
    private javax.swing.JLabel specialist_label;
    private javax.swing.JTextField work_place;
    private javax.swing.JLabel work_place_label;
    // End of variables declaration//GEN-END:variables
}
