/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emedi;

/**
 *
 * @author sria
 */
public class Medicine_by_name extends javax.swing.JFrame {

    /**
     * Creates new form Medicine_by_name
     */
    public Medicine_by_name() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_medicine = new javax.swing.JTable();
        generic_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medicines By Generic  Name");
        setMaximumSize(new java.awt.Dimension(1026, 583));
        setMinimumSize(new java.awt.Dimension(1026, 583));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1026, 583));
        getContentPane().setLayout(null);

        jScrollPane1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        table_medicine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_medicine.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        table_medicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Tablet", "ACE", "Paracetamol+Caffeine ", "500mg+65mg", "NAPA,NAPA Extra "},
                {"Tablet", "CTZ", "Cetirizine Dihydrochloride", "10 mg", "RIZ,Alatrol"},
                {"Cream", "Pevisone", "Econazole Nitrate 1%  , Triamcinolone Acetonide 0.1%", "10 g", " Pevitin,Econate Plus"},
                {"Cream", "Savlon", "Chlorhexedine Hydrochloride + Cetrimide", "30g", "Savior"},
                {"Capsule", "Seclo", "Omeprazole", "20mg", "Prilosec,Losec"},
                {"Tablet", "Migranil", "Pizotifen Malate", "0.5 mg", "AntiGrain"},
                {"Syrup", "Ambrox", "Ambroxol  Hydrochloride", "100ml", "ACOREX "},
                {"Tablet", "Flagyl", "Metronidazole", "400mg", "Amodis,Flamyd"},
                {"Syrup", "Nectar", "Glycerol +Liquid Sugar", "100ml", "HONYCOL,HUNNY"},
                {"Tablet ", "Loratin", "Loratadine", "10 mg", "Loren,LTDIN,ORADINE"},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Brand Name ", "Generic Name", "Weight", "Alternative Pharmaceutic Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_medicine.setToolTipText("");
        table_medicine.setMaximumSize(new java.awt.Dimension(800, 300));
        table_medicine.setName(""); // NOI18N
        table_medicine.setRowHeight(35);
        jScrollPane1.setViewportView(table_medicine);
        if (table_medicine.getColumnModel().getColumnCount() > 0) {
            table_medicine.getColumnModel().getColumn(0).setMinWidth(70);
            table_medicine.getColumnModel().getColumn(0).setPreferredWidth(70);
            table_medicine.getColumnModel().getColumn(0).setMaxWidth(70);
            table_medicine.getColumnModel().getColumn(1).setMinWidth(180);
            table_medicine.getColumnModel().getColumn(1).setPreferredWidth(180);
            table_medicine.getColumnModel().getColumn(1).setMaxWidth(180);
            table_medicine.getColumnModel().getColumn(3).setMinWidth(100);
            table_medicine.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_medicine.getColumnModel().getColumn(3).setMaxWidth(100);
            table_medicine.getColumnModel().getColumn(4).setMinWidth(240);
            table_medicine.getColumnModel().getColumn(4).setPreferredWidth(240);
            table_medicine.getColumnModel().getColumn(4).setMaxWidth(240);
        }
        table_medicine.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 990, 400);

        generic_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/generic.png"))); // NOI18N
        getContentPane().add(generic_Label);
        generic_Label.setBounds(40, -70, 890, 282);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicine_name.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1026, 583);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicine_by_name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicine_by_name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicine_by_name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicine_by_name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Medicine_by_name().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel generic_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_medicine;
    // End of variables declaration//GEN-END:variables
}
