/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emedi;

/**
 *
 * @author sria
 */
public class Primary_Treatment extends javax.swing.JFrame {

    /**
     * Creates new form Primary_Treatment
     */
    public Primary_Treatment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        disease_label = new javax.swing.JLabel();
        select_disease = new javax.swing.JComboBox<>();
        medicine_u_need = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        side_effect_area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Symptom_Area = new javax.swing.JTextArea();
        caution_label = new javax.swing.JLabel();
        side_effect_label = new javax.swing.JLabel();
        symptom_label = new javax.swing.JLabel();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Primary Treatment");
        setMaximumSize(new java.awt.Dimension(102, 583));
        setMinimumSize(new java.awt.Dimension(1026, 583));
        setPreferredSize(new java.awt.Dimension(1026, 583));
        getContentPane().setLayout(null);

        disease_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseases_Label.jpg"))); // NOI18N
        disease_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(disease_label);
        disease_label.setBounds(10, 10, 130, 50);

        select_disease.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        select_disease.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select_Diseases", "Gastritis", "Fever", "Migraine", "Allergy", "Dysentery", "Cough" }));
        select_disease.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        select_disease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_diseaseActionPerformed(evt);
            }
        });
        getContentPane().add(select_disease);
        select_disease.setBounds(150, 10, 170, 50);

        medicine_u_need.setBackground(new java.awt.Color(219, 212, 212));
        medicine_u_need.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        medicine_u_need.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        medicine_u_need.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_u_needActionPerformed(evt);
            }
        });
        getContentPane().add(medicine_u_need);
        medicine_u_need.setBounds(460, 10, 550, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicines_You_need.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 10, 110, 50);

        side_effect_area.setBackground(new java.awt.Color(233, 198, 198));
        side_effect_area.setColumns(20);
        side_effect_area.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        side_effect_area.setRows(5);
        side_effect_area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(side_effect_area);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(622, 137, 390, 430);

        Symptom_Area.setBackground(new java.awt.Color(233, 198, 198));
        Symptom_Area.setColumns(20);
        Symptom_Area.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Symptom_Area.setRows(5);
        Symptom_Area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(Symptom_Area);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 140, 350, 430);

        caution_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caution.jpg"))); // NOI18N
        caution_label.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caution !!!", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeSerif", 3, 24), new java.awt.Color(244, 244, 244))); // NOI18N
        getContentPane().add(caution_label);
        caution_label.setBounds(370, 260, 230, 190);

        side_effect_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/side_effect.jpg"))); // NOI18N
        getContentPane().add(side_effect_label);
        side_effect_label.setBounds(670, 70, 310, 60);

        symptom_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/symptom.jpg"))); // NOI18N
        getContentPane().add(symptom_label);
        symptom_label.setBounds(10, 70, 310, 61);

        background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/primary_treatment.jpg"))); // NOI18N
        background_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        background_label.setMaximumSize(new java.awt.Dimension(1026, 583));
        background_label.setMinimumSize(new java.awt.Dimension(1026, 583));
        background_label.setPreferredSize(new java.awt.Dimension(1026, 583));
        getContentPane().add(background_label);
        background_label.setBounds(0, 0, 1026, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_diseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_diseaseActionPerformed
        // TODO add your handling code here:
        if (select_disease.getSelectedItem().equals("Gastritis"))
            
        {
            Object[] gastritis = null;
            String dGastric;
            dGastric = String.format(" Seclo ( Omeprzole 20mg)", gastritis);
            medicine_u_need.setText(dGastric);
            
            String sGastric = String.format("  Symptom of Gastritis:\n\n "
                    + "* Nausea or recurrent upset stomach \n\n" +
                      "* Abdominal bloating \n" +
                      "* Abdominal pain \n" +
                      "* Vomiting \n" +
                      "* Indigestion \n" +
                      "* Burning or gnawing feeling in the \n"
                    + "* stomach between meals or at night \n" 
                    + "* Hiccups \n" +
                      "* Loss of appetite \n" +
                      "* Black, tarry stools ", gastritis);
            Symptom_Area.setText(sGastric);
            
            String eGastric=String.format("  Side effets of Omeprazole :\n\n"
                    + "* Diarrohea (watery and severe;\n"
                    + "   May also be bloody) \n" +
                      "* Increased sensitivity to sunlight \n" +
                      "* Joint pain \n" +
                      "* Mild skin rash or itching \n" +
                      "* Muscle aches or cramps \n" +
                      "* Pain or burning in the mouth or throat \n" +
                      "* Sensation of burning, prickling,\n"
                    + "  or numbness \n" +
                      "* Signs of liver damage \n"
                    + "   (yellow skin or eyes, dark urine,\n"
                    + "   loss of appetite, abdominal pain,\n"
                    + "   fever, and fatigue)\n"
                    + "\n  Stop taking the medication and seek\n "
                    + "   immediate medical attention if any of \n"
                    + "   the following occur:\n\n" +
                      "* Signs of an allergic reaction\n"
                    + "   (e.g., difficulty breathing, hives,\n"
                    + "   swelling of the face or throat) \n" +
                      "* Signs of bleeding in the stomach\n"
                    + "   (e.g., bloody, black, or tarry stools\n"
                    + "  spitting up of blood, vomiting blood or\n"
                    + "  material that looks like coffee grounds)\n" +
                      "* Signs of a severe skin reaction\n"
                    + "   such as blistering, peeling,\n"
                    + "   a rash covering a large area of the body,\n"
                    + "   a rash that spreads quickly, or a \n"
                    + "   rash combined with fever or discomfort \n", gastritis);
            side_effect_area.setText(eGastric);
            
        }
       
        
        if (select_disease.getSelectedItem().equals("Fever"))
            
        {
            Object[] fever = null;
            String dFever;
            dFever = String.format(" ACE (Paracetamol 500mg + Caffeine 65 mg)", fever);
            medicine_u_need.setText(dFever);
            
            String sFever = String.format(" Symptom of Fever: \n\n"
                   +"* Temperature will be Higher than\n"
                   +"    99 deg Farenheit\n" +
                    "* Severe headache \n" +
                    "* Unusual skin rash, especially if the\n"
                    +"   rash rapidly worsens \n" +
                    "* Unusual sensitivity to bright light \n" +
                    "* Stiff neck and pain when you\n"
                  + "    bend your head forward \n" +
                    "* Mental confusion \n" +
                    "* Persistent vomiting \n" +
                    "* Difficulty breathing or chest pain \n" +
                    "* Abdominal pain or pain when urinating \n" +
                    "* Convulsions or seizures \n\n"
                   +"  Fever or elevated body temperature might\n"
                  + "  be caused by:\n\n" +
                    "* A virus \n" +
                    "* A bacterial infection \n" +
                    "* Heat exhaustion \n" +
                    "* Certain inflammatory conditions such as\n"
                   +"   rheumatoid arthritis — inflammation of \n"
                   +"   the lining of your joints (synovium) \n" +
                    "* A malignant tumor \n" +
                    "* Some medications, such as antibiotics\n "
                  + "   and drugs used to treat\n"
                   +"   high blood pressure or seizures\n" +
                    "* Some immunizations, such as the ,\n"
                   +"   diphtheria tetanus and acellular\n"
                   +"   pertussis (DTaP) or pneumococcal vaccine", fever);
            Symptom_Area.setText(sFever);
            
            String eFever=String.format(
                    "  Side effects of Paracetamol\n"
                  + "  are rare but can include:\n\n" +
                    "* An allergic reaction, which can cause\n"
                  + "   a rash and swelling \n" +
                    "* Flushing, low blood pressure and\n"
                  + "   a fast heartbeat – this can sometimes\n"
                  + "   happen when paracetamol is given in\n"
                  + "   hospital into a vein in your arm \n" +
                    "* Blood disorders, such as thrombocytopenia\n"
                  + "  (low number of platelet cells) and\n"
                  + "  leukopenia(low number of white blood cells)\n" +
                    "* Liver and kidney damage,\n"
                  + "   if you take too much (overdose)\n"
                  + "   this can be fatal in severe cases", fever);
            side_effect_area.setText(eFever);
        }
        
        if (select_disease.getSelectedItem().equals("Allergy"))
            
        {
            Object[] allergy = null;
            String dAllergy;
            dAllergy = String.format(" Alatrol (Cetirizine Di-Hydrocloride 10mg) ", allergy);
            medicine_u_need.setText(dAllergy);
            
            String sAllergy = String.format(" Symptom of Allergy : \n\n"
                    + "* Sneezing and an itchy, runny or\n"
                    + "   blocked nose (allergic rhinitis) \n" +
                      "* Itchy, red, watering eyes (conjunctivitis) \n" 
                   +  "* Wheezing, chest tightness,\n"
                    + "   shortness of breath and a cough \n"+
                      "* A raised, itchy, red rash (hives) \n" +
                      "* Swollen lips, tongue, eyes or face \n" +
                      "* Tummy pain, feeling sick,\n"
                    + "   vomiting or diarrhoea \n" +
                      "* Dry, red and cracked skin ",allergy);
            Symptom_Area.setText(sAllergy);
            
            String eAllergy = String.format(" Cetirizine side effects :\n\n"+
                    " * Fast, pounding, or uneven heartbeat;\n" +
                    " * Weakness, tremors (uncontrolled shaking),\n   or sleep problems (insomnia);\n" +
                    " * Severe restless feeling, hyperactivity;\n" +
                    " * Confusion;\n" +
                    " * Problems with vision; or\n" +
                    " * Urinating less than usual or not at all.\n\n"
                    + " Less serious side effects may include:\n\n" +
                    " * Dizziness, drowsiness;\n" +
                    " * Tired feeling;\n" +
                    " * Dry mouth;\n" +
                    " * Sore throat, cough;\n" +
                    " * Nausea, constipation; or\n" +
                    " * Headache.\n\n"
                    + " Caution : This is not a complete list"
                    + "\n    of side effects and others may occur."
                    + "\n    Tell your doctor about any unusual "
                    + "\n    or bothersome side effect."
                    , allergy);
            side_effect_area.setText(eAllergy);
        }
            
            
        if (select_disease.getSelectedItem().equals("Migraine"))
        
        {
            Object[] migraine = null;
            String dMigraine = String.format(" Migranil (Pizotifen 0.5 mg) ", migraine);
            medicine_u_need.setText(dMigraine);
                
            String sMigraine =String.format("  During a migraine, you may experience:\n\n" +
                        "* Pain on one side or both sides of your head.\n" +
                        "* Pain that feels throbbing or pulsing.\n" +
                        "* Sensitivity to light, sounds, and \n"
                        + " sometimes smells and touch.\n" +
                        "* Nausea and vomiting.\n" +
                        "* Blurred vision.\n" +
                        "* Lightheadedness, sometimes\n"
                        + "   followed by fainting.", migraine);
            Symptom_Area.setText(sMigraine);
                
            String eMigraine =String.format("  Side Effect of Pizotifen :\n\n" +
                        "* Patients with glaucoma\n"
                        + "   (raised pressure in your eyes);\n" +
                        "* Patients with problems passing urine\n"
                        + "   such as an enlarged prostate gland;\n" +
                        "* Patients with kidney problems;\n" +
                        "* Patients with liver problems;\n" +
                        "* Patients with a history of epilepsy;\n" +
                        "* Woman who are pregnant,\n"
                        + "   or might be pregnant. "
                      + "\n\n Caution : It should not be used in:\n"
                    + "  * Patients who are allergic (hypersensitive)\n"
                    + "     to pizotifen or any of the other ingredients\n"
                    + "  * Woman who are breast feeding;\n"
                    + "  * Children under 2 years of age. ", migraine);
            side_effect_area.setText(eMigraine);
        }
        
        if (select_disease.getSelectedItem().equals("Cough"))
           
        {
                Object[] cough = null;
                String dcough = String.format(" Ambrox (Ambroxol Hydrochloride 100ml) ", cough);
                medicine_u_need.setText(dcough);
                
                String scough =String.format("  Symptom of Cough : \n\n"
                      + "* A runny or stuffy nose \n" +
                        "* A feeling of liquid running down the back\n"
                      + "   of your throat (postnasal drip) \n" +
                        "* Frequent throat clearing and sore throat \n" +
                        "* Hoarseness \n" +
                        "* Wheezing and shortness of breath \n" +
                        "* Heartburn or a sour taste in your mouth \n" +
                        "* In rare cases, coughing up blood ", cough);
                Symptom_Area.setText(scough);
                
                String ecough =String.format(" Side effects of Ambroxol Hydrochloride : \n\n"
                        + "* Nausea or Indigestion\n"
                        + "* Diarrhea\n"
                        + "* Allergic Reaction\n", cough);
                side_effect_area.setText(ecough);
           }
        
        if(select_disease.getSelectedItem().equals("Dysentery"))
            
        {
            Object[] dysentery = null;
            String ddysentery = String.format(" Amodis (Metronidazole 400 mg)+ Oral Saline ", dysentery);
            medicine_u_need.setText(ddysentery);
                
            String sdysentery =String.format("  Symptoms of Dysentery :\n\n" +
                    "* Watery diarrhea initially that may evolve\n"
                  + "   to contain mucus and blood.\n" +
                    "* Loss of appetite.\n" +
                    "* Straining during bowel movements, with\n"
                  + "   accompanying rectal pain.\n" +
                    "* Abdominal pain; body aches.\n" +
                    "* Nausea and vomiting.\n" +
                    "* Rapid dehydration and weight loss.", dysentery);
            Symptom_Area.setText(sdysentery);
                
            String edysentery =String.format("  Side effects of Flagyl :\n\n" +
                    "* Stomach pain, diarrhea;\n" +
                    "* Dizziness, loss of balance;\n" +
                    "* Daginal itching or discharge;\n" +
                    "* Dry mouth or unpleasant metallic taste;\n" +
                    "* Cough, sneezing, runny or stuffy nose;\n" +
                    "* Swollen or sore tongue.", dysentery);
            side_effect_area.setText(edysentery);
            
        }
        
        
        
        
        
    }//GEN-LAST:event_select_diseaseActionPerformed

    private void medicine_u_needActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_u_needActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_u_needActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Primary_Treatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Primary_Treatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Primary_Treatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Primary_Treatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Primary_Treatment().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Symptom_Area;
    private javax.swing.JLabel background_label;
    private javax.swing.JLabel caution_label;
    private javax.swing.JLabel disease_label;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField medicine_u_need;
    private javax.swing.JComboBox<String> select_disease;
    private javax.swing.JTextArea side_effect_area;
    private javax.swing.JLabel side_effect_label;
    private javax.swing.JLabel symptom_label;
    // End of variables declaration//GEN-END:variables
}
