
package emedi;

/**
 *
 * @author sria
 */
public class WelCome_eMedicine extends javax.swing.JFrame {

    /**
     * Creates new form WelCome_eMedicine
     */
    public WelCome_eMedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_Priamry = new javax.swing.JButton();
        button_medicine_name = new javax.swing.JButton();
        button_consult_with_doc = new javax.swing.JButton();
        button_astro = new javax.swing.JButton();
        bannerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To E-Medicine");
        setMaximumSize(new java.awt.Dimension(1026, 583));
        setMinimumSize(new java.awt.Dimension(1026, 583));
        setPreferredSize(new java.awt.Dimension(1026, 583));
        getContentPane().setLayout(null);

        button_Priamry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button1.jpg"))); // NOI18N
        button_Priamry.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        button_Priamry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PriamryActionPerformed(evt);
            }
        });
        getContentPane().add(button_Priamry);
        button_Priamry.setBounds(740, 290, 260, 50);

        button_medicine_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/generic_name.jpg"))); // NOI18N
        button_medicine_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        button_medicine_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_medicine_nameActionPerformed(evt);
            }
        });
        getContentPane().add(button_medicine_name);
        button_medicine_name.setBounds(680, 360, 320, 40);

        button_consult_with_doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button3.jpg"))); // NOI18N
        button_consult_with_doc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        button_consult_with_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_consult_with_docActionPerformed(evt);
            }
        });
        getContentPane().add(button_consult_with_doc);
        button_consult_with_doc.setBounds(680, 430, 320, 50);

        button_astro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button4.jpg"))); // NOI18N
        button_astro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        button_astro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_astroActionPerformed(evt);
            }
        });
        getContentPane().add(button_astro);
        button_astro.setBounds(800, 510, 200, 40);

        bannerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banner3.jpg"))); // NOI18N
        bannerLabel.setLabelFor(bannerLabel);
        bannerLabel.setAutoscrolls(true);
        getContentPane().add(bannerLabel);
        bannerLabel.setBounds(0, 0, 1024, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_astroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_astroActionPerformed

        About_Astro_03 obj = new About_Astro_03();
        obj.setVisible(true);
    }//GEN-LAST:event_button_astroActionPerformed

    private void button_medicine_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_medicine_nameActionPerformed
        // TODO add your handling code here:
        Medicine_by_name obj=new Medicine_by_name();
        obj.setVisible(true);
    }//GEN-LAST:event_button_medicine_nameActionPerformed

    private void button_PriamryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PriamryActionPerformed
        // TODO add your handling code here:
        Primary_Treatment obj=new Primary_Treatment();
        obj.setVisible(true);
    }//GEN-LAST:event_button_PriamryActionPerformed

    private void button_consult_with_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_consult_with_docActionPerformed
        // TODO add your handling code here:
        consult obj = new consult();
        obj.setVisible(true);
    }//GEN-LAST:event_button_consult_with_docActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelCome_eMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelCome_eMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelCome_eMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelCome_eMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WelCome_eMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerLabel;
    private javax.swing.JButton button_Priamry;
    private javax.swing.JButton button_astro;
    private javax.swing.JButton button_consult_with_doc;
    private javax.swing.JButton button_medicine_name;
    // End of variables declaration//GEN-END:variables
}
